import java.util.Vector;
class CollectionVector2
{
public static void main(String args[])
{
Vector<String>mammals=new Vector<>();
mammals.add("dog");
mammals.add(1,"Cat");
System.out.println("Vector:"+mammals);
Vector<String>animals=new Vector<>();
animals.add("Crocodile");
animals.addAll(mammals);
System.out.println("New vector:"+animals);
Vector<String>friends=new Vector<>();
friends.add("sai");
friends.add("jyothish");
friends.add("sameer");
System.out.println("Friends:"+friends);
Vector<String>fruits=new Vector<>();
fruits.add("Apple");
fruits.add("mango");
fruits.add("banana");
System.out.println("Friends:"+fruits);
Vector<String>Vegetables=new Vector<>();
Vegetables.add("Apple");
Vegetables.add("mango");
Vegetables.add("banana");
System.out.println("Vegetables:"+Vegetables);
Vector<String>AnimalProduce=new Vector<>();
AnimalProduce.add("Apple");
AnimalProduce.add("mango");
AnimalProduce.add("banana");
System.out.println("AnimalProduce:"+AnimalProduce);
Vector<String>DairyProducts=new Vector<>();
DairyProducts.add("Milk");
DairyProducts.add("cheese");
DairyProducts.add("Butter");
System.out.println("DairyProducts:"+DairyProducts);
Vector<String>BakeryProducts=new Vector<>();
BakeryProducts.add("Whole_wheat");
BakeryProducts.add("Cakes");
BakeryProducts.add("Egg puffs");
System.out.println("BakeryProducts:"+BakeryProducts);
Vector<String>Condiments=new Vector<>();
Condiments.add("Salt");
Condiments.add("pepper");
Condiments.add("Sugar");
System.out.println("Condiments:"+Condiments);
Vector<String>IndianSpecies=new Vector<>();
IndianSpecies.add("Cardamom");
IndianSpecies.add("Zeera");
IndianSpecies.add("Tumeric");
System.out.println("IndianSpecies:"+IndianSpecies);
Vector<String>OilsAndSauces=new Vector<>();
OilsAndSauces.add("OliveOil");
OilsAndSauces.add("MusturdOil");
OilsAndSauces.add("SoySauce");
System.out.println("OilsAndSauces:"+OilsAndSauces);
Vector<String>GrainsLegumes=new Vector<>();
GrainsLegumes.add("Atta");
GrainsLegumes.add("Rice");
GrainsLegumes.add("Pasta");
System.out.println("GrainsLegumes:"+GrainsLegumes);
Vector<String>Legumes=new Vector<>();
Legumes.add("Chickpeas");
Legumes.add("kidneybeans");
Legumes.add("beans");
System.out.println("Legumes:"+Legumes);
Vector<String>Snacks=new Vector<>();
Snacks.add("Almonds");
Snacks.add("Papad");
Snacks.add("Honey");
System.out.println("Snacks:"+Snacks);
Vector<String>CleanigSupplies=new Vector<>();
CleanigSupplies.add("Dishwash");
CleanigSupplies.add("Detergent");
CleanigSupplies.add("Shaving cream");
System.out.println("CleanigSupplies:"+CleanigSupplies);
Vector<String>ToiletCleaner=new Vector<>();
ToiletCleaner.add("FloorCleaner");
ToiletCleaner.add("Shampoo");
ToiletCleaner.add("TissuePaper");
System.out.println("ToiletCleaner:"+ToiletCleaner);
}
}